### ISSUE TITLE
Dependency missing?

### ISSUE THREAD

**Issue by jppgks** [FaustXVI/linkedin-to-latex#1]
Hi, I'm getting the following error on `node html2Latex.js > cv.tex && make && make clean`

```js
TypeError: Cannot read property '$' of undefined
    at Object.done (.../linkedin-to-latex/html2Latex.js:25:19)
    at reportInitError (.../linkedin-to-latex/node_modules/jsdom/lib/jsdom.js:414:12)
    at ReadStream.resourceLoader.readFile (.../linkedin-to-latex/node_modules/jsdom/lib/jsdom.js:174:9)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at fs.js:1942:12
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by FaustXVI** [comment]
Thanks for the issue.
I stopped maintaining this repo a long time ago :/
Maybe I should delete it actually :/
Looking at the code and you're error. It seems like the window object is not given. Since I indeed manage badly my dependencies (no `package.lock` file) it may be an update issue.
Please try to remove the `^` charaters of the `package.json` file and try again (with `npm install)`.
If this is not working, then it's a problem that worth investigation but I am afraid I won't have much time to fix it.
I'll be happy to look at a PR though.
Thanks
